# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a9ffcf2f9f7e3ab0220bc184f05470a261f87c98346433b6913fe569d7bf7104a0b8b9c733a529dbdfb021a674805784ffe7cd38d7f5cbe506ec0115b97795e

test:
  secret_key_base: c90786fbd4cbf1ff2139609ad8ad26fd865670cdc085fec4feecab56f4707b74d7861547aac81b5bf81b6948f53da60861ebb2f49059ad181a05782cda14d04f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
